services:
    nginx:
        image: nginx
        container_name: nginx
        ports:
            - "80:80"
            - "443:443"
        restart: always
        volumes:
            - ./vhost.conf:/etc/nginx/conf.d/default.conf:ro
            - ./certs:/etc/nginx/certs:ro
            - ./certs:/etc/ssl:ro
        networks:
            - app_network

networks:
    app_network:
        driver: bridge
